## Module 4
### Task 6: Attitude Error Evaluation

In [1]:
import numpy as np
from attitude import Attitude
from misc_functions import create_submission_txt
att_lmo = Attitude('lmo')

# Initial conditions
sigma_bn_0 = att_lmo.mrp_bn_0
b_omega_bn = att_lmo.omega_bn_0
x0 = np.hstack([sigma_bn_0,b_omega_bn])

# Determining the tracking error
tracking_error_sun = att_lmo.tracking_error(0,x0,'sun',True)
tracking_error_nadir = att_lmo.tracking_error(0,x0,'nadir',True)
tracking_error_gmo = att_lmo.tracking_error(0,x0,'gmo',True)

# Creating submission txt files
create_submission_txt('submission_files/m4_t6_gmo_w.txt',tracking_error_gmo['b_omega_br'])
create_submission_txt('submission_files/m4_t6_gmo_s.txt',tracking_error_gmo['sigma_br'])

create_submission_txt('submission_files/m4_t6_nad_w.txt',tracking_error_nadir['b_omega_br'])
create_submission_txt('submission_files/m4_t6_nad_s.txt',tracking_error_nadir['sigma_br'])

create_submission_txt('submission_files/m4_t6_sun_w.txt',tracking_error_sun['b_omega_br'])
create_submission_txt('submission_files/m4_t6_sun_s.txt',tracking_error_sun['sigma_br'])

sun pointing frame at time t = 0:
    BR = [[ 0.45777778  0.88888889  0.01777778]
 [ 0.87111111 -0.44444444 -0.20888889]
 [-0.17777778  0.11111111 -0.97777778]]
    sigma_br = [-0.77542077 -0.47386825  0.04307893]
    b_omega_br = [ 0.01745329  0.03054326 -0.03839724]
nadir pointing frame at time t = 0:
    BR = [[-0.30281131  0.66452519 -0.68316293]
 [ 0.56122589  0.70368369  0.43572328]
 [ 0.7702797  -0.25146678 -0.58603212]]
    sigma_br = [0.26226523 0.55470457 0.03942405]
    b_omega_br = [ 0.01684883  0.03092879 -0.03891576]
gmo pointing frame at time t = 0:
    BR = [[-0.07147075  0.43840389  0.89593189]
 [-0.51181898  0.75483985 -0.4101928 ]
 [-0.85611522 -0.48787173  0.17043446]]
    sigma_br = [ 0.01697198 -0.38280275  0.2076131 ]
    b_omega_br = [ 0.01729709  0.03065744 -0.03843687]


### Task 7: Numerial Attitude Simulator

In [3]:
from attitude import Attitude
from plotting_functions import plot_2d
from misc_functions import vector_extract,create_submission_txt
import numpy as np

# Setup
lmo = Attitude('lmo')
X0 = np.hstack((lmo.mrp_bn_0,lmo.omega_bn_0))
u = lambda x,t: np.array([0.01,-0.01,0.02]) # N*m
tspan = [0,500]

# Integrating
attitude_simulated_controlled = lmo.attitude_propagation(X0,tspan,u)
attitude_simulated_uncontrolled = lmo.attitude_propagation(X0,tspan,None)

# Plotting
sxc,syc,szc = vector_extract(attitude_simulated_controlled['sigma'])
tc = attitude_simulated_controlled['time']
sxu,syu,szu = vector_extract(attitude_simulated_uncontrolled['sigma'])
tu = attitude_simulated_uncontrolled['time']
name = ['sx_uncontrolled','sy_uncontrolled','sz_uncontrolled','sx_controlled','sy_controlled','sz_controlled']
plot_2d(y=[sxu,syu,szu,sxc,syc,szc],x=[tu,tu,tu,tc,tc,tc],line_name=name,title='Simulated Omega',xlabel='Time (mins)',ylabel='sigma')

## Plotting H and T
H_controlled = attitude_simulated_controlled['H_norm']
H_uncontrolled = attitude_simulated_uncontrolled['H_norm']
plot_2d(y=[H_uncontrolled,H_controlled],x=[tu,tc],line_name=['Uncontrolled','Controlled'],title='Angular Momentum Norm',xlabel='Time (s)',ylabel='Angular Momentum (m^2/s)')

T_controlled = attitude_simulated_controlled['T']
T_uncontrolled = attitude_simulated_uncontrolled['T']
plot_2d(y=[T_uncontrolled,T_controlled],x=[tu,tc],line_name=['Uncontrolled','Controlled'],title='Kinetic Energy',xlabel='Time (s)',ylabel='Energy (kgm/s^2)')

su = [np.linalg.norm(v) for v in attitude_simulated_uncontrolled['sigma']]
sc = [np.linalg.norm(v) for v in attitude_simulated_controlled['sigma']]
plot_2d(y=[su,sc],x=[tu,tc],line_name=['Uncontrolled','Controlled'],title='MRP Norm',xlabel='Time (s)',ylabel='MRP ()')

## Submission files
create_submission_txt('submission_files/m4_t7_sigma500.txt',attitude_simulated_uncontrolled['sigma'][500])
create_submission_txt('submission_files/m4_t7_HB500.txt',attitude_simulated_uncontrolled['H'][500])
create_submission_txt('submission_files/m4_t7_T500.txt',attitude_simulated_uncontrolled['T'][500])
create_submission_txt('submission_files/m4_t7_HN500.txt',attitude_simulated_uncontrolled['BN'][500].T@attitude_simulated_uncontrolled['H'][500])
create_submission_txt('submission_files/m4_t7_sigma_controlled100.txt',attitude_simulated_controlled['sigma'][100])
